groups:
- name: trading_critical
  rules:
  - alert: TradingSystemDown
    expr: up{job="crypto-ai-bot"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Trading system is down"
      description: "The crypto bot has been down for more than 1 minute"
  
  - alert: HighMemoryUsage
    expr: (process_resident_memory_bytes / 1024 / 1024) > 512
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage is above 512MB"
