global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'crypto-ai-bot'
    metrics_path: /metrics
    scrape_interval: 30s
    static_configs:
      - targets: ['crypto-ai-bot-production.up.railway.app']
        labels:
          app: 'crypto-ai-bot'
          environment: 'production'